DEFAULT_REFRESH_INTERVAL = 300
DEFAULT_TIMEFRAME_DAYS = 30
MAX_REFRESH_INTERVAL = 86400
MIN_REFRESH_INTERVAL = 60

CACHE_TTL_DASHBOARD_CONFIG = 3600
CACHE_TTL_DASHBOARD_DATA = 300
CACHE_TTL_WIDGET_DATA = 180
CACHE_TTL_METRIC_CALCULATION = 60
CACHE_TTL_QUERY_RESULT = 600

ROLE_ADMIN = "admin"
ROLE_EDITOR = "editor"
ROLE_VIEWER = "viewer"
